import React from "react";
import Head from "next/head";
import "animate.css/animate.min.css";
import ScrollAnimation from "react-animate-on-scroll";

import Header from "../components/Header";

function Comingsoon() {
    return (
        <div>
            <Head>
                <title>Agelessteez</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"images/logo_color.png"} />
            </Head>
            <main>
                <Header activeIndex={4} /> 
                <ScrollAnimation 
                    animateIn="animate__fadeInUp" 
                    animateOut="animate__fadeOutDown"
                    className="animation"
                >
                    <div className="print-h w-full h-screen flex justify-center mt-44">
                        Comming Soon....
                    </div>
                </ScrollAnimation>
            </main>
        </div>
    )
}

export default Comingsoon;