import React from "react";
import Head from 'next/head';
import "animate.css/animate.min.css";
import ScrollAnimation from "react-animate-on-scroll";

import Header from '../components/Header';

function Comming() {
    return (
        <div>
            <Head>
                <title>Agelessteez</title>
                <meta name="description" content="Generated by create next app" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <main>
                <Header /> 
                <ScrollAnimation 
                    animateIn='animate__fadeInUp' 
                    animateOut='animate__fadeOutDown'
                >
                    <div className="print-h w-full h-screen flex justify-center mt-44">
                        Comming Soon....
                    </div>
                </ScrollAnimation>
            </main>
        </div>
    )
}

export default Comming;