import React from "react";
import Head from "next/head";
import "animate.css/animate.min.css";
import ScrollAnimation from "react-animate-on-scroll";

import Header from "../components/Header";

function Mint() {
    return (
        <div>
            <Head>
                <title>Agelessteez</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"images/logo_color.png"} />
            </Head>
            <main>
                <Header activeIndex={4} />   
                    <div className="opa-20 mint-background z-0 " ></div>
                    <div className="mint-section mt-28">
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div className="grid grid-cols-2">
                                <ScrollAnimation 
                                    animateIn="animate__fadeInUp" 
                                    animateOut="animate_fadeOutLeft"
                                    className="h-full animation"
                                >
                                    <div className="flex flex-col justify-center items-center md:items-end">                                    
                                        <div className="w-4/6 relative flex">
                                            <img src={"images/mint_circle.png"} className="" />
                                            <div className="absolute w-full flex flex-col justify-center items-center top-0 left-0">
                                                <div className="relative w-full flex justify-center items-center flex-col mt-4">
                                                    <p className="h-n">10</p>
                                                    <p className="h-d">Days</p>
                                                </div>
                                            </div>
                                        </div>                                    
                                    </div>
                                </ScrollAnimation>
                                <ScrollAnimation 
                                    animateIn="animate__fadeInDown" 
                                    animateOut="animate_fadeOutUp"
                                    className="h-full animation"
                                >
                                    <div className="flex flex-col justify-center items-center">
                                        <div className="w-4/6 relative flex">
                                            <img src={"images/mint_circle.png"} className="" />
                                            <div className="absolute w-full flex flex-col justify-center items-center top-0 left-0">
                                                <div className="relative w-full flex justify-center items-center flex-col mt-4">
                                                    <p className="h-n">10</p>
                                                    <p className="h-d">Days</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </ScrollAnimation>
                            </div>
                            <ScrollAnimation 
                                animateIn="animate__zoomIn" 
                                animateOut="animate_fadeOut"
                                className="h-full animation flex justify-center"
                            >
                                <div className="w-3/5 md:w-full h-full relative">
                                    <button className="w-full h-full relative mint-block">
                                        Mint
                                    </button>
                                </div>
                            </ScrollAnimation>
                            <div className="grid grid-cols-2">
                                <ScrollAnimation 
                                    animateIn="animate__fadeInDown" 
                                    animateOut="animate_fadeOutUp"
                                    className="h-full animation"
                                >
                                    <div className="flex flex-col justify-center items-center">
                                        <div className="w-4/6 relative flex">
                                            <img src={"images/mint_circle.png"} className="" />
                                            <div className="absolute w-full flex flex-col justify-center items-center top-0 left-0">
                                                <div className="relative w-full flex justify-center items-center flex-col mt-4">
                                                    <p className="h-n">10</p>
                                                    <p className="h-d">Days</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </ScrollAnimation>
                                <ScrollAnimation 
                                    animateIn="animate__fadeInUp" 
                                    animateOut="animate_fadeOutLeft"
                                    className="h-full animation"
                                >
                                    <div className="flex flex-col justify-center items-center md:items-start">
                                        <div className="w-4/6 relative flex">
                                            <img src={"images/mint_circle.png"} className="" />
                                            <div className="absolute w-full flex flex-col justify-center items-center top-0 left-0">
                                                <div className="relative w-full flex justify-center items-center flex-col mt-4">
                                                    <p className="h-n">10</p>
                                                    <p className="h-d">Days</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </ScrollAnimation>
                            </div>
                        </div>
                        <ScrollAnimation 
                            animateIn="animate__fadeInUp" 
                            animateOut="animate_fadeOutUp"
                            className="h-full animation"
                        >
                            <div className="text-center mt-1">
                                <p className="t-m">
                                    0/25 Mints Available
                                </p>
                            </div>
                        </ScrollAnimation>
                        <div className="imgae-block grid grid-cols-1 md:grid-cols-4 gap-4 mt-14">
                            <ScrollAnimation 
                                animateIn="animate__fadeInLeft" 
                                animateOut="animate_fadeOutLeft"
                                className="h-full animation"
                            >
                                <div className="flex justify-center md:justify-end">                                
                                    <div className="p-back-part">
                                        <div className="p-back">
                                            <img src={"images/mint_man_back.png"} />
                                        </div>
                                    </div>                               
                                </div>           
                            </ScrollAnimation>    
                            <ScrollAnimation 
                                animateIn="animate__zoomIn" 
                                animateOut="animate_zoomOut"
                                className="h-full animation flex justify-center items-end"
                            >              
                                <div className="p-mint">
                                    <img src={"images/mint_man.png"} />
                                </div>
                            </ScrollAnimation>
                            <ScrollAnimation 
                                animateIn="animate__zoomIn" 
                                animateOut="animate_zoomOut"
                                className="h-full animation flex justify-start items-center mt-8"
                            >  
                                <div className="p-shirt">
                                    <img src={"images/mint_shirt.png"} />
                                </div>
                            </ScrollAnimation>
                            <ScrollAnimation 
                                animateIn="animate__fadeInRight" 
                                animateOut="animate_fadeOutRight"
                                className="h-full animation flex justify-start items-center"
                            >  
                            <div className="post-part relative mt-14 md:mt-0">
                                <div className="p-post-part relative">   
                                    <img src={"images/post_man.png"} className="post_man z-10" />                                 
                                </div>                                
                            </div>
                            </ScrollAnimation>
                        </div>
                        <footer className="flex justify-center w-full" style={{ marginTop: "40px" }}>
                            <div className="flex justify-between w-1/2 md:w-1/4 lg:w-1/5 xl:w-1/6">
                                {/* <ScrollAnimation 
                                    animateIn="animate__fadeInLeft" 
                                    animateOut="animate__fadeOutLeft"
                                > */}
                                    <a href="https://twitter.com/AgelessTeez" target="_blank" rel="noreferrer" className="footer-icon">
                                        <img src={"images/twitter.png"} className="w-2/4 m-auto" />
                                    </a>
                                    <a href="https://discord.gg/xBe4hu4tgp" target="_blank" rel="noreferrer" className="footer-icon">
                                        <img src={"images/discord.png"} className="w-2/4 m-auto" />
                                    </a>
                                    <a href="https://www.instagram.com/agelessteez/" target="_blank" rel="noreferrer" className="footer-icon">
                                        <img src={"images/instrgram.png"} className="w-2/4 m-auto" />
                                    </a>
                                    {/* <a className="footer-icon">
                                        <img src={"images/boat.png"} className="w-2/4 m-auto" />
                                    </a> */}
                                {/* </ScrollAnimation> */}
                            </div>
                        </footer>
                    </div>
            </main>
        </div>
    )
}

export default Mint;